
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIS = 2;
  public static final int PTVIRG = 10;
  public static final int POW = 7;
  public static final int MENOSUNARIO = 12;
  public static final int INTEIRO = 11;
  public static final int MENOS = 3;
  public static final int MULT = 4;
  public static final int MOD = 6;
  public static final int EOF = 0;
  public static final int PARENTESQ = 8;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int PARENTDIR = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV",
  "MOD",
  "POW",
  "PARENTESQ",
  "PARENTDIR",
  "PTVIRG",
  "INTEIRO",
  "MENOSUNARIO"
  };
}

